### ISSUE TITLE
wont save a metafile see below

### ISSUE THREAD

**Issue by moetruman** [mbudnek/hubitat-fan-thermostat#10]
Metadata Error:Please check if you inadvertently pasted driver code into apps code window on line 1

**Comment by mbudnek** [comment]
Have you checked that you've not pasted the driver into the apps code window like it says?  This project consists of two apps (fan-thermostat-parent.groovy and fan-thermostat-child.groovy) and one driver (fan-thermostat-driver.groovy).  They must be entered into the appropriate places in Hubitat.

**Comment by moetruman** [comment]
Bingo

Sent from my iPhone

On Apr 11, 2021, at 6:47 PM, Miles Budnek ***@***.***> wrote:

﻿

Have you checked that you've not pasted the driver into the apps code window like it says? This project consists of two apps (fan-thermostat-parent.groovy and fan-thermostat-child.groovy) and one driver (fan-thermostat-driver.groovy). They must be entered into the appropriate places in Hubitat.
