### ISSUE TITLE
Java errors when using only switch with no fancontroller

### ISSUE THREAD

**Issue by samstreak** [mbudnek/hubitat-fan-thermostat#11]
021-05-17 18:26:45.066 errorgroovy.lang.GroovyRuntimeException: Ambiguous method overloading for method java.lang.Integer#multiply.
Cannot resolve which method to invoke for [null] due to overlapping prototypes between:
	[class java.lang.Character]
	[class java.lang.Number] on line 235 (childEventHandler)

2021-05-17 18:41:30.165 errorjava.lang.NullPointerException: Cannot invoke method reverse() on null object on line 174 (childEventHandler)

I have created a fork and updated it with functioning code but never did much with GitHub so I'm not sure how to get it into a PR here...

https://github.com/samstreak/hubitat-fan-thermostat/commit/7d123c9021a9e5a49d1e74dd9405b040d14890d6

**Comment by mbudnek** [comment]
Thanks for the report and the contribution!  I did just a bit of cleanup on your changes and merged them in #12.
